apiVersion: v1
kind: Service
metadata:
  name: wil-playground-service
  namespace: dev
spec:
  selector:
    app: wil-playground
  ports:
  - protocol: TCP
    port: 80           # Ingress talks to this port
    targetPort: 8888   # This matches your containerPort in deployment.yaml
  type: LoadBalancer
